__author__ = 'stas'

nucleotides = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}


def dna_complement(dna):
    res = ""
    for n in dna:
        res += nucleotides[n]
    return res[::-1]

if __name__ == "__main__":
    print "Complementing a Strand of DNA(REVC task)"
    data = "TGGCCTCCTTTCATTAAAATTTTGTAACATGTACGAGATTTGATCCCAGCAAAAATAATTCTTCGCCCGTGCTGACGACGTTGCTTAATACACATCCGTAGAATACACGAATAACTCCATGCATATTTCGGTTATGGTATCTAGACAGGGGCACGGGCTATTATGCCAAGTAGAACTTATGTCGTTACCGGGGAAGGGCCTTGGTCTGGTATGGTAAGTTGCTGTTGACCCAAGTCTACCGCCCAAAACACAAGCTCCACCGGTCTAACTAGCGAATGGGTATCGGAGGATATCGCTTGAATGTAGTATCTGTGAAGTGAGGCTTTAGTCCATTAAACCGCTACGGTAAAACTGTGTAGTAAGGGCTTCCTAGAACTCTATCCTACCAAGTCCCTTGAGAACACCGGCATAGGTGGGGCGAAAGCCTAATCCGTTCACAACGACTAGACTGGTCTCATACCAATGAAATGTGGATTTCGCGTGCCAGAGAGACGAGACTGAGATACTGCCACAGGCTCAGACTAAAGCCGTTTTCATTCGTATGAACCCAGCGTGATGCCTATTTTCTTTGTAAGATGACTTGTCCCCGGGGAGGCGAAGTGCACCCGGCGATTATGCGCACCCAAGTTTCTTCGGCCAAGAAGCCCGAACACGTTTCCCGCAGAGAGCCACTCCACTGACATGTTCACGTGTAACGGGCGACTCGGTTCTTATGCGGGGGCACGAGAACCTAAAGATAATTTGAGCGTACTAGTGAGTCCCTATCATGTATCTTTATAACCTGCATCTATTGATGCCCTCGGTCGTCGTAACTGTCCACGTTTGCGAAAGGCAGAATTCAATCTCAAATCACAACAACAGCTTCAAACCGGGCGGATACGGACTCTTATAAGCGGGTTTGAA"
    print (dna_complement("GGATCCGATGCTACGTACGATGGATCC"))